const festivals = [
  // 2025 National and Major Festivals
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-01-01",
    "day": "Wednesday",
    "name": "New Year's Day",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-01-14",
    "day": "Tuesday",
    "name": "Makar Sankranti / Pongal / Uttarayan",
    "type": "FESTIVAL",
    "regions": ["All", "TN", "GJ"],
    "description": "Harvest festival with kite flying and feasts"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-01-26",
    "day": "Sunday",
    "name": "Republic Day",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-02-26",
    "day": "Wednesday",
    "name": "Maha Shivaratri",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival honoring Lord Shiva"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-03-13",
    "day": "Thursday",
    "name": "Holika Dahan",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Bonfires marking the eve of Holi"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-03-14",
    "day": "Friday",
    "name": "Holi",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Festival of colors celebrating spring"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-03-30",
    "day": "Sunday",
    "name": "Hindu New Year / Ugadi / Gudi Padwa",
    "type": "FESTIVAL",
    "regions": ["AP", "TS", "KA", "MH"],
    "description": "Regional New Year celebrations"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-03-31",
    "day": "Monday",
    "name": "Eid al-Fitr",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"],
    "description": "Islamic festival marking the end of Ramadan"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-04-06",
    "day": "Sunday",
    "name": "Rama Navami",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating Lord Rama’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-04-10",
    "day": "Thursday",
    "name": "Mahavir Jayanti",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Jain festival honoring Lord Mahavir’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-04-14",
    "day": "Monday",
    "name": "Dr. B.R. Ambedkar Jayanti / Vaisakhi",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All", "PB"],
    "description": "Birth anniversary of Dr. Ambedkar and Sikh New Year"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-04-18",
    "day": "Friday",
    "name": "Good Friday",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Christian observance of Jesus Christ’s crucifixion"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-05-12",
    "day": "Monday",
    "name": "Buddha Purnima",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Buddhist festival celebrating Buddha’s birth, enlightenment, and death"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-06-07",
    "day": "Saturday",
    "name": "Eid al-Adha / Bakrid",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"],
    "description": "Islamic Festival of Sacrifice"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-06-27",
    "day": "Friday",
    "name": "Rath Yatra",
    "type": "FESTIVAL",
    "regions": ["OR"],
    "description": "Hindu festival with chariot processions in Puri"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-07-06",
    "day": "Sunday",
    "name": "Muharram",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Islamic day of mourning"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-08-09",
    "day": "Saturday",
    "name": "Raksha Bandhan",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating sibling bonds"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-08-15",
    "day": "Friday",
    "name": "Independence Day",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-08-16",
    "day": "Saturday",
    "name": "Janmashtami",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating Lord Krishna’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-08-26",
    "day": "Tuesday",
    "name": "Onam",
    "type": "FESTIVAL",
    "regions": ["KL"],
    "description": "Kerala’s harvest festival with boat races and pookalam"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-09-05",
    "day": "Friday",
    "name": "Ganesh Chaturthi",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["MH", "GJ", "KA"],
    "description": "Hindu festival honoring Lord Ganesha"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-09-22",
    "day": "Monday",
    "name": "Navratri Begins",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Nine-night Hindu festival worshiping Goddess Durga"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-10-01",
    "day": "Wednesday",
    "name": "Dussehra / Vijayadashami",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating victory of good over evil"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-10-02",
    "day": "Thursday",
    "name": "Gandhi Jayanti",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-10-20",
    "day": "Monday",
    "name": "Diwali / Deepavali",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Festival of Lights celebrating victory of light over darkness"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-10-22",
    "day": "Wednesday",
    "name": "Govardhan Puja",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Hindu festival honoring Lord Krishna"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-10-23",
    "day": "Thursday",
    "name": "Bhai Dooj",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating sibling bonds"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-11-05",
    "day": "Wednesday",
    "name": "Guru Nanak Jayanti",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Sikh festival celebrating Guru Nanak’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2025,
    "date": "2025-12-25",
    "day": "Thursday",
    "name": "Christmas",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Christian festival celebrating Jesus Christ’s birth"
  },
  // 2026 National and Major Festivals (Estimated Dates)
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-01-01",
    "day": "Thursday",
    "name": "New Year's Day",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-01-14",
    "day": "Wednesday",
    "name": "Makar Sankranti / Pongal / Uttarayan",
    "type": "FESTIVAL",
    "regions": ["All", "TN", "GJ"],
    "description": "Harvest festival with kite flying and feasts"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-01-26",
    "day": "Monday",
    "name": "Republic Day",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-02-14",
    "day": "Saturday",
    "name": "Maha Shivaratri",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival honoring Lord Shiva"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-03-02",
    "day": "Monday",
    "name": "Holika Dahan",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Bonfires marking the eve of Holi"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-03-03",
    "day": "Tuesday",
    "name": "Holi",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Festival of colors celebrating spring"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-03-20",
    "day": "Friday",
    "name": "Eid al-Fitr",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"],
    "description": "Islamic festival marking the end of Ramadan"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-03-25",
    "day": "Wednesday",
    "name": "Hindu New Year / Ugadi / Gudi Padwa",
    "type": "FESTIVAL",
    "regions": ["AP", "TS", "KA", "MH"],
    "description": "Regional New Year celebrations"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-03-26",
    "day": "Thursday",
    "name": "Rama Navami",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating Lord Rama’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-03-30",
    "day": "Monday",
    "name": "Mahavir Jayanti",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Jain festival honoring Lord Mahavir’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-04-03",
    "day": "Friday",
    "name": "Good Friday",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Christian observance of Jesus Christ’s crucifixion"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-04-14",
    "day": "Tuesday",
    "name": "Dr. B.R. Ambedkar Jayanti / Vaisakhi",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All", "PB"],
    "description": "Birth anniversary of Dr. Ambedkar and Sikh New Year"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-05-01",
    "day": "Friday",
    "name": "Buddha Purnima",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Buddhist festival celebrating Buddha’s birth, enlightenment, and death"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-05-27",
    "day": "Wednesday",
    "name": "Eid al-Adha / Bakrid",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"],
    "description": "Islamic Festival of Sacrifice"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-06-15",
    "day": "Monday",
    "name": "Rath Yatra",
    "type": "FESTIVAL",
    "regions": ["OR"],
    "description": "Hindu festival with chariot processions in Puri"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-06-25",
    "day": "Thursday",
    "name": "Muharram",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Islamic day of mourning"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-07-29",
    "day": "Wednesday",
    "name": "Raksha Bandhan",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating sibling bonds"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-08-05",
    "day": "Wednesday",
    "name": "Janmashtami",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating Lord Krishna’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-08-15",
    "day": "Saturday",
    "name": "Independence Day",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-08-25",
    "day": "Tuesday",
    "name": "Ganesh Chaturthi",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["MH", "GJ", "KA"],
    "description": "Hindu festival honoring Lord Ganesha"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-09-04",
    "day": "Friday",
    "name": "Onam",
    "type": "FESTIVAL",
    "regions": ["KL"],
    "description": "Kerala’s harvest festival with boat races and pookalam"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-09-11",
    "day": "Friday",
    "name": "Navratri Begins",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Nine-night Hindu festival worshiping Goddess Durga"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-09-20",
    "day": "Sunday",
    "name": "Dussehra / Vijayadashami",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating victory of good over evil"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-10-02",
    "day": "Friday",
    "name": "Gandhi Jayanti",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["All"]
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-10-09",
    "day": "Friday",
    "name": "Diwali / Deepavali",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Festival of Lights celebrating victory of light over darkness"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-10-11",
    "day": "Sunday",
    "name": "Govardhan Puja",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Hindu festival honoring Lord Krishna"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-10-12",
    "day": "Monday",
    "name": "Bhai Dooj",
    "type": "FESTIVAL",
    "regions": ["Most States"],
    "description": "Hindu festival celebrating sibling bonds"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-11-24",
    "day": "Tuesday",
    "name": "Guru Nanak Jayanti",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Sikh festival celebrating Guru Nanak’s birth"
  },
  {
    "country": "India",
    "iso": "IN",
    "year": 2026,
    "date": "2026-12-25",
    "day": "Friday",
    "name": "Christmas",
    "type": "PUBLIC_HOLIDAY",
    "regions": ["Most States"],
    "description": "Christian festival celebrating Jesus Christ’s birth"
  }
]

export default festivals