import React from 'react';
import { Mail } from 'lucide-react';
import cn from 'classnames';

interface TermsOfServiceProps {
  content?: {
    introduction?: string;
    acceptance?: string;
    userResponsibilities?: string;
    contentOwnership?: string;
    termination?: string;
    liability?: string;
    governingLaw?: string;
    updates?: string;
  };
  contactEmail?: string;
  className?: string;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({
  content = {
    introduction:
      'These Terms of Service govern your use of [Your App Name], a content creation platform. By using our app, you agree to these terms. Last updated: May 28, 2025.',
    acceptance:
      'You accept these Terms of Service by creating an account or using our platform. If you do not agree, please do not use our services.',
    userResponsibilities:
      'You agree not to use our platform to create harmful, illegal, or misleading content (e.g., hate speech, spam). You are responsible for the content you generate using our AI tools, including Social Media Posts, Blog Articles, and Promotional Posts.',
    contentOwnership:
      'You retain ownership of the content you create (e.g., posts, articles), but grant us a non-exclusive, worldwide license to store and process it to provide our services. We own all platform content, including templates and AI models.',
    termination:
      'We may suspend or terminate your account if you violate these terms, such as by creating prohibited content. You can also delete your account at any time via "Account Settings."',
    liability:
      'We are not liable for damages caused by your use of our app, including content generated by our AI. Our service is provided "as is" without warranties of uninterrupted access.',
    governingLaw:
      'These terms are governed by the laws of India. Any disputes will be resolved in the courts of [Your City], India.',
    updates:
      'We may update these terms periodically. You will be notified of changes via email or an in-app banner. Continued use of the app after updates constitutes acceptance of the new terms.',
  },
  contactEmail = 'support@yourapp.com',
  className,
}) => {
  return (
    <div className={cn('py-16 px-4 bg-gray-50 dark:bg-gray-900 transition-colors duration-300', className)}>
      <div className="container mx-auto max-w-4xl">
        {/* Header */}
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            Terms of Service
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            Understand the rules for using our platform. Last updated: May 28, 2025.
          </p>
        </div>

        {/* Content */}
        <div className="space-y-8 text-gray-600 dark:text-gray-300">
          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Introduction
            </h3>
            <p>{content.introduction}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Acceptance of Terms
            </h3>
            <p>{content.acceptance}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              User Responsibilities
            </h3>
            <p>{content.userResponsibilities}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Content Ownership
            </h3>
            <p>{content.contentOwnership}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Account Termination
            </h3>
            <p>{content.termination}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Limitation of Liability
            </h3>
            <p>{content.liability}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Governing Law
            </h3>
            <p>{content.governingLaw}</p>
          </section>

          <section>
            <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
              Updates to Terms
            </h3>
            <p>{content.updates}</p>
          </section>
        </div>

        {/* Contact Section */}
        <div className="mt-12 text-center">
          <p className="text-lg text-gray-600 dark:text-gray-300 mb-4">
            Have questions about our terms? Contact us!
          </p>
          <a
            href={`mailto:${contactEmail}`}
            className="inline-flex items-center px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <Mail className="w-5 h-5 mr-2" />
            Email Us
          </a>
        </div>
      </div>
    </div>
  );
};